
package CalculatorGui;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author charles
 */
public class GradingGui extends javax.swing.JFrame implements ActionListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GradingGui.class.getName());

    /**
     * Creates new form GradingSystemGui
     */
    public GradingGui() {
        initComponents();
        setLocationRelativeTo(null);
        provide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_name = new javax.swing.JTextField();
        txt_physics = new javax.swing.JTextField();
        txt_chemistry = new javax.swing.JTextField();
        txt_maths = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_percentage = new javax.swing.JTextField();
        txt_grade = new javax.swing.JTextField();
        lbl_title = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_physics = new javax.swing.JLabel();
        lbl_chemistry = new javax.swing.JLabel();
        lbl_maths = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_percentage = new javax.swing.JLabel();
        lbl_grade = new javax.swing.JLabel();
        btn_calculate = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_name.addActionListener(this::txt_nameActionPerformed);

        txt_physics.addActionListener(this::txt_physicsActionPerformed);

        txt_chemistry.addActionListener(this::txt_chemistryActionPerformed);

        txt_percentage.addActionListener(this::txt_percentageActionPerformed);

        lbl_title.setText("Calculate Your Grade");

        lbl_name.setText("Your name:");

        lbl_physics.setText("Physics:");

        lbl_chemistry.setText("Chemistry:");

        lbl_maths.setText("Maths:");

        lbl_total.setText("Your total marks:");

        lbl_percentage.setText("Percentage:");

        lbl_grade.setText("Your grade:");

        btn_calculate.setText("Calculate");

        btn_clear.setText("Clear");

        btn_exit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_chemistry)
                                    .addComponent(lbl_maths))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_chemistry)
                                    .addComponent(txt_maths))
                                .addGap(45, 45, 45)
                                .addComponent(lbl_grade))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_physics)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_physics))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_name)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(lbl_percentage))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_total)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_total, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txt_percentage)
                            .addComponent(txt_grade)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btn_calculate)
                        .addGap(40, 40, 40)
                        .addComponent(btn_clear)
                        .addGap(44, 44, 44)
                        .addComponent(btn_exit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_name)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_total, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_physics)
                    .addComponent(lbl_percentage)
                    .addComponent(txt_physics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_percentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_chemistry)
                    .addComponent(lbl_grade)
                    .addComponent(txt_chemistry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_maths)
                    .addComponent(txt_maths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_exit)
                    .addComponent(btn_calculate)
                    .addComponent(btn_clear))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_percentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_percentageActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        txt_physics.requestFocus();
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_physicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_physicsActionPerformed
        txt_chemistry.requestFocus();
    }//GEN-LAST:event_txt_physicsActionPerformed

    private void txt_chemistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chemistryActionPerformed
        txt_maths.requestFocus();
    }//GEN-LAST:event_txt_chemistryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GradingGui().setVisible(true));
    }
    @Override
    public void actionPerformed(ActionEvent e){
        String caption = e.getActionCommand();
        if(caption.equals("Calculate")){
            double physics = Double.parseDouble(txt_physics.getText());
            double chemistry = Double.parseDouble(txt_chemistry.getText());
            double maths = Double.parseDouble(txt_maths.getText());
            double total = physics + chemistry + maths;
            double percentage = Math.round((total/300) * 100);
            char grade = grade(percentage);
            if(grade == 'O'){
                JOptionPane.showMessageDialog(null, "Invalid mark entered\nAll marks must lie between 0 and 100 for the total to be below 300");
            }
            txt_total.setText(String.valueOf(total));
            txt_percentage.setText(String.valueOf(percentage));
            txt_grade.setText(String.valueOf(grade));
        }
        else if (caption.equals("Clear")){
            txt_name.setText("");
            txt_physics.setText("");
            txt_chemistry.setText("");
            txt_maths.setText("");
            txt_percentage.setText("");
            txt_total.setText("");
            txt_grade.setText("");
        }
        else if(caption.equals("Exit")){
            int choice = JOptionPane.showConfirmDialog(null, "Do you want to exit?");
            if (choice == 0)
                System.exit(0);
            else if (choice == 1)
                JOptionPane.showMessageDialog(null, "The application won't shut down . \n Enjoy your xpace");
                
        }
    }
    public void provide(){
        btn_calculate.addActionListener(this);
        btn_clear.addActionListener(this);
        btn_exit.addActionListener(this);
        txt_total.setEditable(false);
        txt_percentage.setEditable(false);
        txt_grade.setEditable(false);
    }
    public char grade(double mark){
        if(mark >= 80 && mark <= 100)
            return 'A';
        else if (mark >= 70 && mark <= 79)
            return 'B';
        else if (mark >= 60 && mark <= 69)
            return 'C';
        else if (mark >= 50 && mark <= 59)
            return 'D';
        else if (mark < 50 && mark >= 0)
            return 'F';
        else
            return 'O';
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel lbl_chemistry;
    private javax.swing.JLabel lbl_grade;
    private javax.swing.JLabel lbl_maths;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_percentage;
    private javax.swing.JLabel lbl_physics;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField txt_chemistry;
    private javax.swing.JTextField txt_grade;
    private javax.swing.JTextField txt_maths;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_percentage;
    private javax.swing.JTextField txt_physics;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
