package CalculatorGui;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author charles
 */
public class PracticeGui extends javax.swing.JFrame implements ActionListener{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PracticeGui.class.getName());

    /**
     * Creates new form PracticeGui
     */
    public PracticeGui() {
        initComponents();
        setLocationRelativeTo(null);
        behavior();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_first = new javax.swing.JLabel();
        lbl_second = new javax.swing.JLabel();
        txt_first = new javax.swing.JTextField();
        txt_second = new javax.swing.JTextField();
        lbl_result = new javax.swing.JLabel();
        txt_result = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTS UG: Stock Management Calculator");

        lbl_first.setText("Enter first Number:");

        lbl_second.setText("Enter second Number:");

        txt_first.addActionListener(this::txt_firstActionPerformed);

        lbl_result.setText("Results:");

        btn_add.setText("ADD");

        btn_reset.setText("RESET");

        btn_exit.setText("EXIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btn_add)
                                .addGap(37, 37, 37)
                                .addComponent(btn_reset)
                                .addGap(38, 38, 38)
                                .addComponent(btn_exit)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_result)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_result, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_second)
                            .addComponent(lbl_first))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_second, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_first, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_first)
                    .addComponent(txt_first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_second)
                    .addComponent(txt_second, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_result)
                    .addComponent(txt_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_reset)
                    .addComponent(btn_exit))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstActionPerformed
        txt_second.requestFocus();
    }//GEN-LAST:event_txt_firstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PracticeGui().setVisible(true));
    }
    
    @Override
    public void actionPerformed(ActionEvent e){
        String caption = e.getActionCommand();
        switch (caption) {
            case "RESET":
                txt_first.setText("");
                txt_second.setText("");
                txt_result.setText("");
                break;
            case "ADD":
                if(txt_first.getText().equals("") || txt_second.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Please fill in both operands");
                }
                try{
                double first = Double.parseDouble(txt_first.getText());
                double second = Double.parseDouble(txt_second.getText());
                double result = first + second;
                txt_result.setText(String.valueOf(result));
                }
                catch (NumberFormatException ewt){
                    System.out.println("Error");
                }
                break;

            case "EXIT":
                System.exit(0);
                break;
            default:
                break;
        }
    }
    public void behavior(){
        txt_result.setEditable(false);
        btn_add.addActionListener(this);
        btn_reset.addActionListener(this);
        btn_exit.addActionListener(this);
        txt_first.addActionListener(this);
        txt_second.addActionListener(this);
        txt_result.addActionListener(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel lbl_first;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JLabel lbl_second;
    private javax.swing.JTextField txt_first;
    private javax.swing.JTextField txt_result;
    private javax.swing.JTextField txt_second;
    // End of variables declaration//GEN-END:variables

}
