/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package charlesk.com.hospital_management_system;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.Connection;
/**
 *
 * @author charles
 */
public class Admissions extends javax.swing.JFrame {
    ResultSet rs;
    PreparedStatement pst;
    Connection con;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admissions.class.getName());

    /**
     * Creates new form Admissions
     */
    public Admissions() {
        initComponents();
        setLocationRelativeTo(null);

        loadPatients();
        loadDoctors();
        loadWards();

        combo_patient.setSelectedIndex(-1);
        combo_doctor.setSelectedIndex(-1);
        combo_ward.setSelectedIndex(-1);
        combo_status.setSelectedIndex(-1);

        loadAdmissions();
        showResultsInTheTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_find = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        lbl_admission_id = new javax.swing.JLabel();
        lbl_discharge_date = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        lbl_admission_reason = new javax.swing.JLabel();
        txt_admission_reason = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();
        discharge_date = new com.toedter.calendar.JDateChooser();
        combo_patient = new javax.swing.JComboBox<>();
        btn_previous = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        admissions_table = new javax.swing.JTable();
        admission_date = new com.toedter.calendar.JDateChooser();
        lbl_admission_date = new javax.swing.JLabel();
        lbl_patient_id = new javax.swing.JLabel();
        combo_ward = new javax.swing.JComboBox<>();
        combo_doctor = new javax.swing.JComboBox<>();
        lbl_ward_id = new javax.swing.JLabel();
        lbl_doctor_id = new javax.swing.JLabel();
        combo_status = new javax.swing.JComboBox<>();
        txt_admission_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_find.setText("FIND");
        btn_find.addActionListener(this::btn_findActionPerformed);

        btn_save.setText("SAVE");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        btn_back.setText("Back");
        btn_back.addActionListener(this::btn_backActionPerformed);

        btn_last.setText("LAST");
        btn_last.addActionListener(this::btn_lastActionPerformed);

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(this::btn_exitActionPerformed);

        btn_first.setText("FIRST");
        btn_first.addActionListener(this::btn_firstActionPerformed);

        lbl_admission_id.setText("Admission id");

        lbl_discharge_date.setText("Discharge Date");

        lbl_status.setText("Status");

        lbl_admission_reason.setText("Admission reason");

        btn_next.setText("NEXT");
        btn_next.addActionListener(this::btn_nextActionPerformed);

        btn_previous.setText("PREVIOUS");
        btn_previous.addActionListener(this::btn_previousActionPerformed);

        admissions_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First name", "Last Name", "Gender", "Date of birth", "Phone", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(admissions_table);

        lbl_admission_date.setText("Admission Date");

        lbl_patient_id.setText("Patient id");

        lbl_ward_id.setText("Ward id");

        lbl_doctor_id.setText("Doctor id");

        combo_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admitted", "Discharged" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_patient_id)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_admission_id)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_admission_id, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_first)
                                .addGap(18, 18, 18)
                                .addComponent(btn_last)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_next)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_previous))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_clear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_exit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_find))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_discharge_date)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(discharge_date, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_doctor_id)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(94, 94, 94)
                                                .addComponent(combo_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(91, 91, 91)
                                                .addComponent(combo_ward, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addComponent(combo_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbl_ward_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_admission_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(admission_date, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_admission_reason)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_status, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_admission_reason, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(combo_status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_admission_id)
                            .addComponent(txt_admission_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addComponent(btn_back))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_patient_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_doctor_id)
                        .addGap(12, 12, 12))
                    .addComponent(combo_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_ward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ward_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_admission_date)
                    .addComponent(admission_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(discharge_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_discharge_date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_admission_reason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_admission_reason))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_status)
                    .addComponent(combo_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear)
                    .addComponent(btn_delete)
                    .addComponent(btn_exit)
                    .addComponent(btn_find))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_previous))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
    String admission_id = txt_admission_id.getText().trim();

    if(admission_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the Admission ID to search");
        txt_admission_id.requestFocus();
        return;
    }

    String sql = "SELECT * FROM admissions WHERE admission_id = ?";

    try(Connection searchCon = DatabaseConnection.getConnection(); 
            PreparedStatement searchPst = searchCon.prepareStatement(sql))
    {
        searchPst.setString(1, admission_id);

        try(ResultSet searchRs = searchPst.executeQuery()){

            if(searchRs.next()){
                displayAdmission(searchRs);
            }else{
                JOptionPane.showMessageDialog(this, "Admission not found");
            }
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error searching admission: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
    Object patient = combo_patient.getSelectedItem();
    Object doctor = combo_doctor.getSelectedItem();
    Object ward = combo_ward.getSelectedItem();
    Object status = combo_status.getSelectedItem();
    java.util.Date admissionDate = admission_date.getDate();
    java.util.Date dischargeDate = discharge_date.getDate();
    String reason = txt_admission_reason.getText().trim();

    if(patient == null){
        JOptionPane.showMessageDialog(this, "Please select a patient");
        return;
    }else if(doctor == null){
        JOptionPane.showMessageDialog(this, "Please select a doctor");
        return;
    }else if(ward == null){
        JOptionPane.showMessageDialog(this, "Please select a ward");
        return;
    }else if(admissionDate == null){
        JOptionPane.showMessageDialog(this, "Please select the admission date");
        return;
    }else if(reason.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the admission reason");
        txt_admission_reason.requestFocus();
        return;
    }else if(status == null){
        JOptionPane.showMessageDialog(this, "Please select the status");
        return;
    }

    String patient_id = patient.toString().split(" - ")[0];
    String doctor_id = doctor.toString().split(" - ")[0];
    String ward_id = ward.toString().split(" - ")[0];

    String sql = "INSERT INTO admissions(patient_id, doctor_id, ward_id, admission_date, discharge_date, admission_reason, status) VALUES (?, ?, ?, ?, ?, ?, ?)";

    try(Connection conn = DatabaseConnection.getConnection(); 
            PreparedStatement pt = conn.prepareStatement(sql)){

        pt.setString(1, patient_id);
        pt.setString(2, doctor_id);
        pt.setString(3, ward_id);
        pt.setDate(4, new java.sql.Date(admissionDate.getTime()));

        if(dischargeDate == null) pt.setNull(5, java.sql.Types.DATE);
        else pt.setDate(5, new java.sql.Date(dischargeDate.getTime()));

        pt.setString(6, reason);
        pt.setString(7, status.toString());

        int rows = pt.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Admission successfully saved");
            clear();
            loadAdmissions();
            showResultsInTheTable();
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error while saving admission: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       try{
        clear();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error while clearing the interface");
    }
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    String admission_id = txt_admission_id.getText().trim();

    if(admission_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter or select an Admission ID to delete");
        txt_admission_id.requestFocus();
        return;
    }

    int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this admission?", "Confirm deletion", JOptionPane.YES_NO_OPTION);

    if(choice != JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM admissions WHERE admission_id = ?";

    try(Connection conn = DatabaseConnection.getConnection(); 
            PreparedStatement pt = conn.prepareStatement(sql)){

        pt.setString(1, admission_id);
        int rows = pt.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Admission deleted successfully");
            clear();
            loadAdmissions();
            showResultsInTheTable();
        }else{
            JOptionPane.showMessageDialog(this, "Admission does not exist");
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Hospital_System().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        try{
            if(rs != null && rs.last()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        try{
            if(rs != null) rs.close();
            if(pst != null) pst.close();
            if(con != null) con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Problem while closing resources: " + e.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        try{
            if(rs != null && rs.first()){
                displayCurrentRow();
            }else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Results have not been loaded");
            else if(rs.next())
            displayCurrentRow();
            else{
                JOptionPane.showMessageDialog(this, "You are at the last row");
                rs.last();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Rocords are not loaded");

            else if(rs.previous()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "You are at the first record");
                rs.first();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_previousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admissions().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser admission_date;
    private javax.swing.JTable admissions_table;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> combo_doctor;
    private javax.swing.JComboBox<String> combo_patient;
    private javax.swing.JComboBox<String> combo_status;
    private javax.swing.JComboBox<String> combo_ward;
    private com.toedter.calendar.JDateChooser discharge_date;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_admission_date;
    private javax.swing.JLabel lbl_admission_id;
    private javax.swing.JLabel lbl_admission_reason;
    private javax.swing.JLabel lbl_discharge_date;
    private javax.swing.JLabel lbl_doctor_id;
    private javax.swing.JLabel lbl_patient_id;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_ward_id;
    private javax.swing.JTextField txt_admission_id;
    private javax.swing.JTextField txt_admission_reason;
    // End of variables declaration//GEN-END:variables
public void loadPatients(){
    String sql = "SELECT patient_id, first_name, last_name FROM patients ORDER BY first_name";

    try(Connection con = DatabaseConnection.getConnection(); PreparedStatement pst = con.prepareStatement(sql); ResultSet rs = pst.executeQuery()){
        combo_patient.removeAllItems();

        while(rs.next()){
            combo_patient.addItem(rs.getString("patient_id") + " - " + rs.getString("first_name") + " " + rs.getString("last_name"));
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading patients: " + e.getMessage());
    }
}
public void loadDoctors(){
    String sql = "SELECT doctor_id, first_name, last_name FROM doctors ORDER BY first_name";

    try(Connection con = DatabaseConnection.getConnection(); PreparedStatement pst = con.prepareStatement(sql); ResultSet rs = pst.executeQuery()){
        combo_doctor.removeAllItems();

        while(rs.next()){
            combo_doctor.addItem(rs.getString("doctor_id") + " - Dr. " + rs.getString("first_name") + " " + rs.getString("last_name"));
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading doctors: " + e.getMessage());
    }
}
public void loadWards(){
    String sql = "SELECT ward_id, ward_name FROM wards ORDER BY ward_name";

    try(Connection con = DatabaseConnection.getConnection(); PreparedStatement pst = con.prepareStatement(sql); ResultSet rs = pst.executeQuery()){
        combo_ward.removeAllItems();

        while(rs.next()){
            combo_ward.addItem(rs.getString("ward_id") + " - " + rs.getString("ward_name"));
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading wards: " + e.getMessage());
    }
}

public void displayAdmission(ResultSet data) throws SQLException{
    txt_admission_id.setText(rs.getString("admission_id"));
    selectComboById(combo_patient, data.getString("patient_id"));
    selectComboById(combo_doctor, data.getString("doctor_id"));
    selectComboById(combo_ward, data.getString("ward_id"));
    admission_date.setDate(data.getDate("admission_date"));
    discharge_date.setDate(data.getDate("discharge_date"));
    txt_admission_reason.setText(data.getString("admission_reason"));
    combo_status.setSelectedItem(data.getString("status"));
}
public void displayCurrentRow() throws SQLException{
    displayAdmission(rs);
}

public void selectComboById(javax.swing.JComboBox<String> combo, String id){
    for(int i = 0; i < combo.getItemCount(); i++){
        if(combo.getItemAt(i).startsWith(id + " - ")){
            combo.setSelectedIndex(i);
            break;
        }
    }
}
public void clear() throws SQLException{
    txt_admission_id.setText("");
    combo_patient.setSelectedIndex(-1);
    combo_doctor.setSelectedIndex(-1);
    combo_ward.setSelectedIndex(-1);
    combo_status.setSelectedIndex(-1);
    admission_date.setDate(null);
    discharge_date.setDate(null);
    txt_admission_reason.setText("");
}
public final void loadAdmissions(){
    String sql = "SELECT * FROM admissions ORDER BY admission_id";

    try{
        con = DatabaseConnection.getConnection();
        pst = con.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        rs = pst.executeQuery();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading admissions: " + e.getMessage());
    }
}
public final void showResultsInTheTable(){
    try{
        DefaultTableModel model = (DefaultTableModel) admissions_table.getModel();
        model.setRowCount(0);

        while(rs.next()){
            Object[] row = {
                rs.getString("admission_id"),
                rs.getString("patient_id"),
                rs.getString("doctor_id"),
                rs.getString("ward_id"),
                rs.getDate("admission_date"),
                rs.getDate("discharge_date"),
                rs.getString("admission_reason"),
                rs.getString("status")
            };

            model.addRow(row);
        }

        rs.beforeFirst();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading admissions: " + e.getMessage());
    }
}

}
