/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package charlesk.com.hospital_management_system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
/**
 *
 * @author charles
 */
public class Appointments extends javax.swing.JFrame {
    ResultSet rs;
    PreparedStatement pst;
    Connection con;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Appointments.class.getName());

    /**
     * Creates new form Appointments
     */
    public Appointments() {
        initComponents();
        SpinnerDateModel timeModel = new SpinnerDateModel();
        spinner_appointment_time.setModel(timeModel);
        spinner_appointment_time.setEditor(new JSpinner.DateEditor(spinner_appointment_time, "HH:mm:ss"));
        setLocationRelativeTo(null);

        loadPatients();
        loadDoctors();

        combo_patient.setSelectedIndex(-1);
        combo_doctor.setSelectedIndex(-1);
        combo_status.setSelectedIndex(-1);

        loadAppointments();
        showResultsInTheTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_appointment_id = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();
        btn_find = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        combo_patient = new javax.swing.JComboBox<>();
        btn_previous = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointments_table = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        appointment_date = new com.toedter.calendar.JDateChooser();
        btn_last = new javax.swing.JButton();
        lbl_appointment_date = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        lbl_patient_id = new javax.swing.JLabel();
        lbl_appointment_id = new javax.swing.JLabel();
        lbl_appointment_time = new javax.swing.JLabel();
        combo_doctor = new javax.swing.JComboBox<>();
        lbl_status = new javax.swing.JLabel();
        lbl_doctor_id = new javax.swing.JLabel();
        combo_status = new javax.swing.JComboBox<>();
        spinner_appointment_time = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_next.setText("NEXT");
        btn_next.addActionListener(this::btn_nextActionPerformed);

        btn_find.setText("FIND");
        btn_find.addActionListener(this::btn_findActionPerformed);

        btn_save.setText("SAVE");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        btn_previous.setText("PREVIOUS");
        btn_previous.addActionListener(this::btn_previousActionPerformed);

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        appointments_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Patient ID", "Doctor ID", "Appointment Date", "Appointment Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(appointments_table);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        btn_back.setText("Back");
        btn_back.addActionListener(this::btn_backActionPerformed);

        btn_last.setText("LAST");
        btn_last.addActionListener(this::btn_lastActionPerformed);

        lbl_appointment_date.setText("Appointment Date");

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(this::btn_exitActionPerformed);

        btn_first.setText("FIRST");
        btn_first.addActionListener(this::btn_firstActionPerformed);

        lbl_patient_id.setText("Patient id");

        lbl_appointment_id.setText("Appointment ID");

        lbl_appointment_time.setText("Appointment Time");

        lbl_status.setText("     Status");

        lbl_doctor_id.setText("Doctor id");

        combo_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scheduled", "Completed", "Cancelled" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_patient_id)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_appointment_id)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_appointment_id, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_first)
                                .addGap(18, 18, 18)
                                .addComponent(btn_last)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_next)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_previous))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_clear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_exit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_find))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_doctor_id)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(94, 94, 94)
                                                .addComponent(combo_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(15, 15, 15)
                                            .addComponent(combo_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lbl_status, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo_status, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_appointment_date)
                                            .addComponent(lbl_appointment_time))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(appointment_date, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(spinner_appointment_time))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_appointment_id)
                            .addComponent(txt_appointment_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addComponent(btn_back))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_patient_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_doctor_id)
                    .addComponent(combo_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(appointment_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_appointment_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_appointment_time, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_appointment_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_status)
                    .addComponent(combo_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear)
                    .addComponent(btn_delete)
                    .addComponent(btn_exit)
                    .addComponent(btn_find))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_previous))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Results have not been loaded");
            else if(rs.next())
            displayCurrentRow();
            else{
                JOptionPane.showMessageDialog(this, "You are at the last row");
                rs.last();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
    String appointment_id = txt_appointment_id.getText().trim();

    if(appointment_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the Appointment ID to search");
        txt_appointment_id.requestFocus();
        return;
    }

    String sql = "SELECT * FROM appointments WHERE appointment_id = ?";

    try(Connection findCon = DatabaseConnection.getConnection(); PreparedStatement findPst = findCon.prepareStatement(sql)){

        findPst.setString(1, appointment_id);

        try(ResultSet findRs = findPst.executeQuery()){

            if(findRs.next()){
                displayAppointment(findRs);
            }else{
                JOptionPane.showMessageDialog(this, "No appointment found with ID " + appointment_id);
            }
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error searching appointment: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
    Object patient = combo_patient.getSelectedItem();
    Object doctor = combo_doctor.getSelectedItem();
    Object status = combo_status.getSelectedItem();
    java.util.Date selectedDate = appointment_date.getDate();
    java.util.Date selectedTime = (java.util.Date) spinner_appointment_time.getValue();

    if(patient == null){
        JOptionPane.showMessageDialog(this, "Please select a patient");
        combo_patient.requestFocus();
        return;
    }else if(doctor == null){
        JOptionPane.showMessageDialog(this, "Please select a doctor");
        combo_doctor.requestFocus();
        return;
    }else if(selectedDate == null){
        JOptionPane.showMessageDialog(this, "Please select the appointment date");
        return;
    }else if(selectedTime == null){
        JOptionPane.showMessageDialog(this, "Please select the appointment time");
        return;
    }else if(status == null){
        JOptionPane.showMessageDialog(this, "Please select the appointment status");
        combo_status.requestFocus();
        return;
    }

    String patient_id = patient.toString().split(" - ")[0];
    String doctor_id = doctor.toString().split(" - ")[0];

    java.sql.Date appointmentDate = new java.sql.Date(selectedDate.getTime());
    java.sql.Time appointmentTime = new java.sql.Time(selectedTime.getTime());

    String sql = "INSERT INTO appointments(patient_id, doctor_id, appointment_date, appointment_time, status) VALUES (?, ?, ?, ?, ?)";

    try(Connection saveCon = DatabaseConnection.getConnection(); PreparedStatement savePst = saveCon.prepareStatement(sql)){

        savePst.setString(1, patient_id);
        savePst.setString(2, doctor_id);
        savePst.setDate(3, appointmentDate);
        savePst.setTime(4, appointmentTime);
        savePst.setString(5, status.toString());

        int rows = savePst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Appointment successfully saved");
            clear();
            loadAppointments();
            showResultsInTheTable();
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error while saving appointment: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Rocords are not loaded");

            else if(rs.previous()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "You are at the first record");
                rs.first();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_previousActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        try{
            clear();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error while clearing the interface");
        }
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    String appointment_id = txt_appointment_id.getText().trim();

    if(appointment_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter or select an Appointment ID to delete");
        txt_appointment_id.requestFocus();
        return;
    }

    int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this appointment?", "Confirm deletion", JOptionPane.YES_NO_OPTION);

    if(choice != JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM appointments WHERE appointment_id = ?";

    try(Connection deleteCon = DatabaseConnection.getConnection(); PreparedStatement deletePst = deleteCon.prepareStatement(sql)){

        deletePst.setString(1, appointment_id);
        int rows = deletePst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Appointment deleted successfully");
            clear();
            loadAppointments();
            showResultsInTheTable();
        }else{
            JOptionPane.showMessageDialog(this, "No appointment with ID " + appointment_id + " exists in the database");
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Hospital_System().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        try{
            if(rs != null && rs.last()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        try{
            if(rs != null) rs.close();
            if(pst != null) pst.close();
            if(con != null) con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Problem while closing resources: " + e.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        try{
            if(rs != null && rs.first()){
                displayCurrentRow();
            }else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Appointments().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser appointment_date;
    private javax.swing.JTable appointments_table;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> combo_doctor;
    private javax.swing.JComboBox<String> combo_patient;
    private javax.swing.JComboBox<String> combo_status;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_appointment_date;
    private javax.swing.JLabel lbl_appointment_id;
    private javax.swing.JLabel lbl_appointment_time;
    private javax.swing.JLabel lbl_doctor_id;
    private javax.swing.JLabel lbl_patient_id;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JSpinner spinner_appointment_time;
    private javax.swing.JTextField txt_appointment_id;
    // End of variables declaration//GEN-END:variables
public void loadPatients(){
    String sql = "SELECT patient_id, first_name, last_name FROM patients ORDER BY first_name, last_name";

    try(Connection patientCon = DatabaseConnection.getConnection(); PreparedStatement patientPst = patientCon.prepareStatement(sql); ResultSet patientRs = patientPst.executeQuery()){
        combo_patient.removeAllItems();

        while(patientRs.next()){
            combo_patient.addItem(patientRs.getString("patient_id") + " - " + patientRs.getString("first_name") + " " + patientRs.getString("last_name"));
        }

        combo_patient.setSelectedIndex(-1);

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading patients: " + e.getMessage());
    }
}
public void loadDoctors(){
    String sql = "SELECT doctor_id, first_name, last_name FROM doctors ORDER BY first_name, last_name";

    try(Connection doctorCon = DatabaseConnection.getConnection(); PreparedStatement doctorPst = doctorCon.prepareStatement(sql); ResultSet doctorRs = doctorPst.executeQuery()){
        combo_doctor.removeAllItems();

        while(doctorRs.next()){
            combo_doctor.addItem(doctorRs.getString("doctor_id") + " - " + doctorRs.getString("first_name") + " " + doctorRs.getString("last_name"));
        }

        combo_doctor.setSelectedIndex(-1);

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading doctors: " + e.getMessage());
    }
}
public void displayAppointment(ResultSet data) throws SQLException{
    txt_appointment_id.setText(data.getString("appointment_id"));
    selectPatient(data.getString("patient_id"));
    selectDoctor(data.getString("doctor_id"));
    appointment_date.setDate(data.getDate("appointment_date"));
    spinner_appointment_time.setValue(data.getTime("appointment_time"));
    combo_status.setSelectedItem(data.getString("status"));
}
public void selectPatient(String patient_id){
    for(int i = 0; i < combo_patient.getItemCount(); i++){
        if(combo_patient.getItemAt(i).startsWith(patient_id + " - ")){
            combo_patient.setSelectedIndex(i);
            break;
        }
    }
}
public void selectDoctor(String doctor_id){
    for(int i = 0; i < combo_doctor.getItemCount(); i++){
        if(combo_doctor.getItemAt(i).startsWith(doctor_id + " - ")){
            combo_doctor.setSelectedIndex(i);
            break;
        }
    }
}
public void clear() throws SQLException{
    txt_appointment_id.setText("");
    combo_patient.setSelectedIndex(-1);
    combo_doctor.setSelectedIndex(-1);
    appointment_date.setDate(null);
    spinner_appointment_time.setValue(new java.util.Date());
    combo_status.setSelectedIndex(-1);
}
public void displayCurrentRow() throws SQLException{
    displayAppointment(rs);
}
public final void loadAppointments(){
    String sql = "SELECT * FROM appointments ORDER BY appointment_id";

    try{
        if(rs != null) rs.close();
        if(pst != null) pst.close();
        if(con != null) con.close();

        con = DatabaseConnection.getConnection();
        pst = con.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        rs = pst.executeQuery();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading appointments: " + e.getMessage());
    }
}
public final void showResultsInTheTable(){
    try{
        DefaultTableModel model = (DefaultTableModel) appointments_table.getModel();
        model.setRowCount(0);

        while(rs.next()){
            Object[] row = {
                rs.getString("appointment_id"),
                rs.getString("patient_id"),
                rs.getString("doctor_id"),
                rs.getDate("appointment_date"),
                rs.getTime("appointment_time"),
                rs.getString("status")
            };

            model.addRow(row);
        }

        rs.beforeFirst();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading appointments: " + e.getMessage());
    }
}
}
