/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package charlesk.com.hospital_management_system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author charles
 */
public class Bills extends javax.swing.JFrame {
    ResultSet rs;
    PreparedStatement pst;
    Connection con;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bills.class.getName());

    /**
     * Creates new form Bills
     */
    public Bills() {
        initComponents();
    setLocationRelativeTo(null);

    loadAppointments();
    combo_appointments.setSelectedIndex(-1);
    combo_status.setSelectedIndex(-1);

    loadBills();
    showResultsInTheTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bill_date = new com.toedter.calendar.JDateChooser();
        lbl_bill_date = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        combo_status = new javax.swing.JComboBox<>();
        combo_appointments = new javax.swing.JComboBox<>();
        lbl_appointment_id = new javax.swing.JLabel();
        txt_bill_id = new javax.swing.JTextField();
        lbl_bill_id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bills_table = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        txt_amount = new javax.swing.JTextField();
        lbl_amount = new javax.swing.JLabel();
        btn_last = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_previous = new javax.swing.JButton();
        btn_find = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_bill_date.setText("Bill Date");

        lbl_status.setText("Status");

        combo_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unpaid", "Paid", "Partial" }));

        lbl_appointment_id.setText("Appointment id");

        lbl_bill_id.setText("Bill id");

        bills_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Appointment ID", "Total Amount", "Bill Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bills_table);

        btn_back.setText("Back");
        btn_back.addActionListener(this::btn_backActionPerformed);

        lbl_amount.setText("Total Amount");

        btn_last.setText("LAST");
        btn_last.addActionListener(this::btn_lastActionPerformed);

        btn_next.setText("NEXT");
        btn_next.addActionListener(this::btn_nextActionPerformed);

        btn_previous.setText("PREVIOUS");
        btn_previous.addActionListener(this::btn_previousActionPerformed);

        btn_find.setText("FIND");
        btn_find.addActionListener(this::btn_findActionPerformed);

        btn_save.setText("SAVE");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(this::btn_exitActionPerformed);

        btn_first.setText("FIRST");
        btn_first.addActionListener(this::btn_firstActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_appointment_id)
                            .addComponent(lbl_bill_id, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_bill_date))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bill_date, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_appointments, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bill_id, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbl_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(lbl_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(combo_status, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_first)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_last)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_next)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_previous))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_save)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_clear)
                                        .addGap(20, 20, 20)
                                        .addComponent(btn_delete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_exit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_find)))
                                .addGap(0, 271, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(618, 618, 618)
                    .addComponent(btn_back)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bill_id)
                    .addComponent(txt_bill_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_appointments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_appointment_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bill_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bill_date))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_status)
                    .addComponent(combo_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_amount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear)
                    .addComponent(btn_delete)
                    .addComponent(btn_exit)
                    .addComponent(btn_find))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_previous))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_back)
                    .addContainerGap(438, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Hospital_System().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        try{
            if(rs != null && rs.last()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Results have not been loaded");
            else if(rs.next())
            displayCurrentRow();
            else{
                JOptionPane.showMessageDialog(this, "You are at the last row");
                rs.last();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Rocords are not loaded");

            else if(rs.previous()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "You are at the first record");
                rs.first();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_previousActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
    String bill_id = txt_bill_id.getText().trim();

    if(bill_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the Bill ID to search");
        txt_bill_id.requestFocus();
        return;
    }

    String sql = "SELECT * FROM bills WHERE bill_id = ?";

    try(Connection findCon = DatabaseConnection.getConnection(); PreparedStatement findPst = findCon.prepareStatement(sql)){

        findPst.setString(1, bill_id);

        try(ResultSet findRs = findPst.executeQuery()){

            if(findRs.next()){
                displayBill(findRs);
            }else{
                JOptionPane.showMessageDialog(this, "No bill found with ID " + bill_id);
            }
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error searching bill: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
    Object appointment = combo_appointments.getSelectedItem();
    Object status = combo_status.getSelectedItem();
    String amount = txt_amount.getText().trim();
    java.util.Date selectedDate = bill_date.getDate();

    if(appointment == null){
        JOptionPane.showMessageDialog(this, "Please select an appointment");
        combo_appointments.requestFocus();
        return;
    }else if(selectedDate == null){
        JOptionPane.showMessageDialog(this, "Please select the bill date");
        return;
    }else if(status == null){
        JOptionPane.showMessageDialog(this, "Please select the bill status");
        combo_status.requestFocus();
        return;
    }else if(amount.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the total amount");
        txt_amount.requestFocus();
        return;
    }

    double totalAmount;

    try{
        totalAmount = Double.parseDouble(amount);

        if(totalAmount <= 0){
            JOptionPane.showMessageDialog(this, "Total amount must be greater than zero");
            txt_amount.requestFocus();
            return;
        }

    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Please enter a valid amount");
        txt_amount.requestFocus();
        return;
    }

    String appointment_id = appointment.toString().split(" - ")[0];
    java.sql.Date billDate = new java.sql.Date(selectedDate.getTime());
    String sql = "INSERT INTO bills(appointment_id, total_amount, bill_date, status) VALUES (?, ?, ?, ?)";

    try(Connection saveCon = DatabaseConnection.getConnection(); PreparedStatement savePst = saveCon.prepareStatement(sql)){

        savePst.setString(1, appointment_id);
        savePst.setDouble(2, totalAmount);
        savePst.setDate(3, billDate);
        savePst.setString(4, status.toString());

        int rows = savePst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Bill successfully saved");
            clear();
            loadBills();
            showResultsInTheTable();
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error while saving bill: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        try{
        clear();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error while clearing the interface");
    }
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    String bill_id = txt_bill_id.getText().trim();

    if(bill_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter or select a Bill ID to delete");
        txt_bill_id.requestFocus();
        return;
    }

    int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this bill?", "Confirm deletion", JOptionPane.YES_NO_OPTION);

    if(choice != JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM bills WHERE bill_id = ?";

    try(Connection deleteCon = DatabaseConnection.getConnection(); PreparedStatement deletePst = deleteCon.prepareStatement(sql)){

        deletePst.setString(1, bill_id);
        int rows = deletePst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Bill deleted successfully");
            clear();
            loadBills();
            showResultsInTheTable();
        }else{
            JOptionPane.showMessageDialog(this, "No bill with ID " + bill_id + " exists in the database");
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        try{
            if(rs != null) rs.close();
            if(pst != null) pst.close();
            if(con != null) con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Problem while closing resources: " + e.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        try{
            if(rs != null && rs.first()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bills().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser bill_date;
    private javax.swing.JTable bills_table;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> combo_appointments;
    private javax.swing.JComboBox<String> combo_status;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_appointment_id;
    private javax.swing.JLabel lbl_bill_date;
    private javax.swing.JLabel lbl_bill_id;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_bill_id;
    // End of variables declaration//GEN-END:variables
public void selectAppointment(String appointment_id){
    for(int i = 0; i < combo_appointments.getItemCount(); i++){
        if(combo_appointments.getItemAt(i).startsWith(appointment_id + " - ")){
            combo_appointments.setSelectedIndex(i);
            break;
        }
    }
}
    public void loadAppointments(){
    String sql = "SELECT a.appointment_id, p.first_name, p.last_name, a.appointment_date FROM appointments a INNER JOIN patients p ON a.patient_id = p.patient_id ORDER BY a.appointment_id";

    try(Connection appointmentCon = DatabaseConnection.getConnection(); PreparedStatement appointmentPst = appointmentCon.prepareStatement(sql); ResultSet appointmentRs = appointmentPst.executeQuery()){
        combo_appointments.removeAllItems();

        while(appointmentRs.next()){
            combo_appointments.addItem(appointmentRs.getString("appointment_id") + " - " + appointmentRs.getString("first_name") + " " + appointmentRs.getString("last_name") + " - " + appointmentRs.getDate("appointment_date"));
        }

        combo_appointments.setSelectedIndex(-1);

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading appointments: " + e.getMessage());
    }
}
    public void displayCurrentRow() throws SQLException{
    displayBill(rs);
}
public void displayBill(ResultSet data) throws SQLException{
    txt_bill_id.setText(data.getString("bill_id"));
    selectAppointment(data.getString("appointment_id"));
    txt_amount.setText(data.getString("total_amount"));
    bill_date.setDate(data.getDate("bill_date"));
    combo_status.setSelectedItem(data.getString("status"));
}
public void clear() throws SQLException{
    txt_bill_id.setText("");
    combo_appointments.setSelectedIndex(-1);
    bill_date.setDate(null);
    combo_status.setSelectedIndex(-1);
    txt_amount.setText("");
}
public final void loadBills(){
    String sql = "SELECT * FROM bills ORDER BY bill_id";

    try{
        if(rs != null) rs.close();
        if(pst != null) pst.close();
        if(con != null) con.close();

        con = DatabaseConnection.getConnection();
        pst = con.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        rs = pst.executeQuery();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading bills: " + e.getMessage());
    }
}
public final void showResultsInTheTable(){
    try{
        DefaultTableModel model = (DefaultTableModel) bills_table.getModel();
        model.setRowCount(0);

        while(rs.next()){
            Object[] row = {
                rs.getString("bill_id"),
                rs.getString("appointment_id"),
                rs.getBigDecimal("total_amount"),
                rs.getDate("bill_date"),
                rs.getString("status")
            };

            model.addRow(row);
        }

        rs.beforeFirst();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading bills: " + e.getMessage());
    }
}

}
