/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package charlesk.com.hospital_management_system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author charles
 */
public class Departments extends javax.swing.JFrame {
    ResultSet rs;
    PreparedStatement pst;
    Connection con;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Departments.class.getName());

    /**
     * Creates new form Departments
     */
    public Departments() {
        initComponents();
        setLocationRelativeTo(null);
        loadDepartments();
        showResultsInTheTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_find = new javax.swing.JButton();
        txt_phone = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        lbl_location = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        lbl_phone = new javax.swing.JLabel();
        btn_first = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        txt_department_id = new javax.swing.JTextField();
        btn_previous = new javax.swing.JButton();
        lbl_diagnoses_id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        departments_table = new javax.swing.JTable();
        txt_location = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_find.setText("FIND");
        btn_find.addActionListener(this::btn_findActionPerformed);

        btn_save.setText("SAVE");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        lbl_name.setText("Department Name");

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        lbl_location.setText("     Location");

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(this::btn_exitActionPerformed);

        lbl_phone.setText("      Phone");

        btn_first.setText("FIRST");
        btn_first.addActionListener(this::btn_firstActionPerformed);

        btn_last.setText("LAST");
        btn_last.addActionListener(this::btn_lastActionPerformed);

        btn_back.setText("Back");
        btn_back.addActionListener(this::btn_backActionPerformed);

        btn_next.setText("NEXT");
        btn_next.addActionListener(this::btn_nextActionPerformed);

        btn_previous.setText("PREVIOUS");
        btn_previous.addActionListener(this::btn_previousActionPerformed);

        lbl_diagnoses_id.setText("Department ID");

        departments_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Department ID", "Department Name", "Location", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(departments_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_diagnoses_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(438, 438, 438)
                        .addComponent(btn_back))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_first)
                                .addGap(18, 18, 18)
                                .addComponent(btn_last)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_next)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_previous))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_clear)
                                .addGap(20, 20, 20)
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_exit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_find))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_department_id, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_location, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_name)
                                        .addComponent(txt_location)
                                        .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_department_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_diagnoses_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_name)
                            .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbl_location, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_phone)
                            .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear)
                    .addComponent(btn_delete)
                    .addComponent(btn_exit)
                    .addComponent(btn_find))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_previous))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
    String department_id = txt_department_id.getText().trim();

    if(department_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the Department ID to search");
        txt_department_id.requestFocus();
        return;
    }

    String sql = "SELECT * FROM departments WHERE department_id = ?";

    try(Connection findCon = DatabaseConnection.getConnection(); PreparedStatement findPst = findCon.prepareStatement(sql)){

        findPst.setString(1, department_id);

        try(ResultSet findRs = findPst.executeQuery()){

            if(findRs.next()){
                displayDepartment(findRs);
            }else{
                JOptionPane.showMessageDialog(this, "No department found with ID " + department_id);
            }
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error searching department: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
    String departmentName = txt_name.getText().trim();
    String location = txt_location.getText().trim();
    String phone = txt_phone.getText().trim();

    if(departmentName.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the department name");
        txt_name.requestFocus();
        return;
    }else if(location.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the department location");
        txt_location.requestFocus();
        return;
    }

    String sql = "INSERT INTO departments(department_name, location, phone) VALUES (?, ?, ?)";

    try(Connection saveCon = DatabaseConnection.getConnection(); PreparedStatement savePst = saveCon.prepareStatement(sql)){

        savePst.setString(1, departmentName);
        savePst.setString(2, location);

        if(phone.isEmpty()) savePst.setNull(3, java.sql.Types.VARCHAR);
        else savePst.setString(3, phone);

        int rows = savePst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Department successfully saved");
            clear();
            loadDepartments();
            showResultsInTheTable();
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error while saving department: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        try
        {clear();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Error while clearing the interface");
        }
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    String department_id = txt_department_id.getText().trim();

    if(department_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter or select a Department ID to delete");
        txt_department_id.requestFocus();
        return;
    }

    int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this department?", "Confirm deletion", JOptionPane.YES_NO_OPTION);

    if(choice != JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM departments WHERE department_id = ?";

    try(Connection deleteCon = DatabaseConnection.getConnection(); PreparedStatement deletePst = deleteCon.prepareStatement(sql)){

        deletePst.setString(1, department_id);
        int rows = deletePst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Department deleted successfully");
            clear();
            loadDepartments();
            showResultsInTheTable();
        }else{
            JOptionPane.showMessageDialog(this, "No department with ID " + department_id + " exists in the database");
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        try{
            if(rs != null) rs.close();
            if(pst != null) pst.close();
            if(con != null) con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Problem while closing resources: " + e.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        try{
            if(rs != null && rs.first()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        try{
            if(rs != null && rs.last()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Hospital_System().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Results have not been loaded");
            else if(rs.next())
            displayCurrentRow();
            else{
                JOptionPane.showMessageDialog(this, "You are at the last row");
                rs.last();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Rocords are not loaded");

            else if(rs.previous()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "You are at the first record");
                rs.first();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_previousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Departments().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous;
    private javax.swing.JButton btn_save;
    private javax.swing.JTable departments_table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_diagnoses_id;
    private javax.swing.JLabel lbl_location;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JTextField txt_department_id;
    private javax.swing.JTextField txt_location;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
public void displayCurrentRow() throws SQLException{
    displayDepartment(rs);
}
    public void displayDepartment(ResultSet data) throws SQLException{
    txt_department_id.setText(data.getString("department_id"));
    txt_name.setText(data.getString("department_name"));
    txt_location.setText(data.getString("location"));
    txt_phone.setText(data.getString("phone"));
}
public void clear() throws SQLException{
    txt_department_id.setText("");
    txt_name.setText("");
    txt_location.setText("");
    txt_phone.setText("");
}
public final void loadDepartments(){
    String sql = "SELECT * FROM departments ORDER BY department_id";

    try{
        if(rs != null) rs.close();
        if(pst != null) pst.close();
        if(con != null) con.close();

        con = DatabaseConnection.getConnection();
        pst = con.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        rs = pst.executeQuery();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading departments: " + e.getMessage());
    }
}
public final void showResultsInTheTable(){
    try{
        DefaultTableModel model = (DefaultTableModel) departments_table.getModel();
        model.setRowCount(0);

        while(rs.next()){
            Object[] row = {
                rs.getString("department_id"),
                rs.getString("department_name"),
                rs.getString("location"),
                rs.getString("phone")
            };

            model.addRow(row);
        }

        rs.beforeFirst();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading departments: " + e.getMessage());
    }
}
}
