/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package charlesk.com.hospital_management_system;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author charles
 */
public class Doctor extends javax.swing.JFrame {
    
ResultSet rs;
PreparedStatement pst;
Connection con;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Doctor.class.getName());

    /**
     * Creates new form Doctor
     */
    public Doctor() {
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_last = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_previous = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctors_table = new javax.swing.JTable();
        btn_find = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        txt_surname = new javax.swing.JTextField();
        lbl_surname = new javax.swing.JLabel();
        lbl_firstname = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        lbl_email = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        lbl_doctors_id = new javax.swing.JLabel();
        lbl_department_id = new javax.swing.JLabel();
        lblb_specialization = new javax.swing.JLabel();
        txt_department_id = new javax.swing.JTextField();
        txt_doctors_id = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_specialization = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_last.setText("LAST");
        btn_last.addActionListener(this::btn_lastActionPerformed);

        btn_next.setText("NEXT");
        btn_next.addActionListener(this::btn_nextActionPerformed);

        btn_previous.setText("PREVIOUS");
        btn_previous.addActionListener(this::btn_previousActionPerformed);

        doctors_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First name", "Last Name", "Doctor's id", "Specialization", "Phone", "Email", "Department id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(doctors_table);

        btn_find.setText("FIND");
        btn_find.addActionListener(this::btn_findActionPerformed);

        btn_save.setText("SAVE");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        txt_surname.addActionListener(this::txt_surnameActionPerformed);

        lbl_surname.setText("SurName");

        lbl_firstname.setText("First Name");

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(this::btn_exitActionPerformed);

        btn_first.setText("FIRST");
        btn_first.addActionListener(this::btn_firstActionPerformed);

        lbl_email.setText("Email");

        lbl_phone.setText("Phone");

        lbl_doctors_id.setText("Doctor's Id");

        lbl_department_id.setText("Department Id");

        lblb_specialization.setText("Specialization");

        txt_specialization.setColumns(20);
        txt_specialization.setRows(5);
        jScrollPane2.setViewportView(txt_specialization);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_doctors_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(lbl_surname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(txt_email)
                                    .addComponent(txt_phone)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_doctors_id, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_department_id, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txt_department_id))
                            .addComponent(lblb_specialization, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_first)
                                .addGap(18, 18, 18)
                                .addComponent(btn_last)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_next)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_previous))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_clear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_exit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_find)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_surname)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_department_id)
                    .addComponent(txt_department_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_firstname)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblb_specialization)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_email)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_phone)
                            .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_doctors_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_doctors_id))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear)
                    .addComponent(btn_delete)
                    .addComponent(btn_exit)
                    .addComponent(btn_find))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_previous))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        try{
            if(rs != null && rs.last()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Results have not been loaded");
            else if(rs.next())
            displayCurrentRow();
            else{
                JOptionPane.showMessageDialog(this, "You are at the last row");
                rs.last();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Rocords are not loaded");

            else if(rs.previous()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "You are at the first record");
                rs.first();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_previousActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        String doctor_id = txt_doctors_id.getText().toUpperCase();
        String sql = "SELECT * FROM student WHERE name = '"+doctor_id+"'";
        if(doctor_id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter the ID to search in the database");
            return;
        }
        try{
            con = DatabaseConnection.getConnection();
            pst = con.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = pst.executeQuery();

            if(rs == null)
            JOptionPane.showMessageDialog(this, "Records have been not loaded");
            else if(rs.next())
            displayCurrentRow();

            else
            JOptionPane.showMessageDialog(this, "No student found with this ID " + doctor_id);

        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        
        String firstname = txt_firstname.getText().trim();
        String surname = txt_surname.getText().trim();
        String phone = txt_phone.getText().trim();
        String email = txt_email.getText().trim();
        String doctor_id = txt_doctors_id.getText().trim();
        String department_id = txt_department_id.getText().trim();
        String specialization = txt_specialization.getText().trim();

        if(firstname.isEmpty() || surname.isEmpty() || specialization.isEmpty() || email.isEmpty() || phone.isEmpty() || doctor_id.isEmpty() || department_id.isEmpty()){
            if(firstname.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill in the firstname");
                txt_firstname.requestFocus();
            }else if(surname.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill in the surname");
                txt_surname.requestFocus();
            }else if(phone.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill in the phone");
                txt_phone.requestFocus();
            }else if(email.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill in the email");
                txt_email.requestFocus();
            }else if(doctor_id.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill in the doctor's ID");
                txt_doctors_id.requestFocus();
            }else if(department_id.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill in the department_id");
                txt_department_id.requestFocus();
            }else if(specialization.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill in the specialization");
                txt_specialization.requestFocus();
            }
            return;
        }
        String sql = "INSERT INTO student(doctor_id, department_id, first_name, last_name, specialization, phone, email) VALUES ('"+doctor_id+"','"+department_id+"', '"+firstname+"', '"+surname+"', '"+specialization+"', '"+phone+"', '"+email+"')";

        try(
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
        ){
            int rows = pst.executeUpdate();
            if (rows > 0){
                JOptionPane.showMessageDialog(this, "Data successfully written into the database");
                clear();
                txt_surname.requestFocus();
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error, while saving in the database");
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_surnameActionPerformed

    }//GEN-LAST:event_txt_surnameActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        try
        {clear();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Error while clearing the interface");
        }
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        String doctors_id = txt_doctors_id.getText().trim();

        String sql_delete = "DELETE FROM student WHERE name = '"+doctors_id+"'";

        try (
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(sql_delete);
        ) {
            int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the record?", "Confirm deletion", JOptionPane.YES_NO_OPTION);
            if(choice == JOptionPane.YES_OPTION){
                
                int rows = pst.executeUpdate();

                if (rows > 0) {
                    JOptionPane.showMessageDialog(this,"Data deleted from database successfully");
                    clear();
                    txt_surname.requestFocus();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Data deleted from database successfully");
                    return;
                }
                    
            } else {
                JOptionPane.showMessageDialog(this, "No Doctor with ID " + doctors_id + " exists in the database.");

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Database error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed

        try {
            con.close();
            rs.close();
            pst.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Problem while closing the resources");
        }
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        try{
            if(rs != null && rs.first()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Doctor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous;
    private javax.swing.JButton btn_save;
    private javax.swing.JTable doctors_table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_department_id;
    private javax.swing.JLabel lbl_doctors_id;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_firstname;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_surname;
    private javax.swing.JLabel lblb_specialization;
    private javax.swing.JTextField txt_department_id;
    private javax.swing.JTextField txt_doctors_id;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextArea txt_specialization;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables

    public void displayCurrentRow() throws SQLException{
        txt_firstname.setText(rs.getString("first_name"));
        txt_surname.setText(rs.getString("last_name"));
        txt_phone.setText(rs.getString("phone"));
        txt_email.setText(rs.getString("email"));
        txt_doctors_id.setText(rs.getString("doctor_id"));
        txt_department_id.setText(rs.getString("department_id"));
        txt_specialization.setText(rs.getString("specialization"));
    }
    
    public void clear() throws SQLException{
        txt_firstname.setText("");
        txt_surname.setText("");
        txt_phone.setText("");
        txt_email.setText("");
        txt_doctors_id.setText("");
        txt_department_id.setText("");
        txt_specialization.setText("");
    }
    
    public final void showResultsInTheTable() {
        try{
            DefaultTableModel model = (DefaultTableModel) doctors_table.getModel();
        
            model.setRowCount(0);
            while(rs.next()){
                Object[] row = {
                    rs.getString("doctor_id"),
                    rs.getString("department_id"),
                    rs.getString("first_name"),
                    rs.getString("last_name"),
                    rs.getString("specialization"),
                    rs.getString("phone"),
                    rs.getString("email")
                };
                    model.addRow(row);
            }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Error loading students" + e.getMessage());
        }
        
    }
    
}
