/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package charlesk.com.hospital_management_system;

/**
 *
 * @author charles
 */
public class Hospital_System extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hospital_System.class.getName());

    /**
     * Creates new form Hospital_System
     */
    public Hospital_System() {
        setLocationRelativeTo(null);
        initComponents();
        txt_area.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_entities = new javax.swing.JMenu();
        menu_people = new javax.swing.JMenu();
        menu_medicine = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu_doctor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        menu_documents = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));

        txt_area.setColumns(20);
        txt_area.setRows(5);
        txt_area.setText("Welcome to the dashboard of Mbarara University Kihumuro Hospital\nKindly follow the above submenus too navigate the schema \nbasing on category.");
        jScrollPane1.setViewportView(txt_area);

        menu_entities.setText("Entities");

        menu_people.setText("People");

        menu_medicine.setText("Doctor");
        menu_medicine.addActionListener(this::menu_medicineActionPerformed);
        menu_people.add(menu_medicine);

        jMenuItem2.setText("Patient");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        menu_people.add(jMenuItem2);

        menu_doctor.setText("Nurse");
        menu_doctor.addActionListener(this::menu_doctorActionPerformed);
        menu_people.add(menu_doctor);

        menu_entities.add(menu_people);

        jMenu2.setText("Services");

        jMenuItem4.setText("Admissions");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Bills");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem9.setText("Diagnoses");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jMenu2.add(jMenuItem9);

        jMenuItem14.setText("Payments");
        jMenuItem14.addActionListener(this::jMenuItem14ActionPerformed);
        jMenu2.add(jMenuItem14);

        menu_entities.add(jMenu2);

        jMenu3.setText("Places");

        jMenuItem7.setText("Departments");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Wards");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu3.add(jMenuItem8);

        jMenuItem13.setText("Rooms");
        jMenuItem13.addActionListener(this::jMenuItem13ActionPerformed);
        jMenu3.add(jMenuItem13);

        menu_entities.add(jMenu3);

        jMenu4.setText("Appointments");

        jMenuItem5.setText("Appointments");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu4.add(jMenuItem5);

        jMenuItem15.setText("Lab Tests");
        jMenuItem15.addActionListener(this::jMenuItem15ActionPerformed);
        jMenu4.add(jMenuItem15);

        menu_entities.add(jMenu4);

        jMenu5.setText("Prescriptions");

        jMenuItem11.setText("Prescriptions");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Prescription Item");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu5.add(jMenuItem12);

        menu_entities.add(jMenu5);

        jMenu6.setText("Medicines");

        jMenuItem10.setText("Medicine");
        jMenuItem10.addActionListener(this::jMenuItem10ActionPerformed);
        jMenu6.add(jMenuItem10);

        menu_entities.add(jMenu6);

        jMenuBar1.add(menu_entities);

        menu_documents.setText("Documents");
        jMenuBar1.add(menu_documents);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_medicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_medicineActionPerformed
        new Doctor().Main();
        this.dispose();
    }//GEN-LAST:event_menu_medicineActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Patients().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menu_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_doctorActionPerformed
        new Nurses().Main();
        this.dispose();
    }//GEN-LAST:event_menu_doctorActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new Admissions().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new Bills().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        new Diagnoses().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        new Payments().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new Departments().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        new Wards().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        new Rooms().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new Appointments().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        Lab_Tests.Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new Prescriptions().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        new Prescription_Items().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new Medicines().Main();
        this.dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Hospital_System().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menu_doctor;
    private javax.swing.JMenu menu_documents;
    private javax.swing.JMenu menu_entities;
    private javax.swing.JMenuItem menu_medicine;
    private javax.swing.JMenu menu_people;
    private javax.swing.JTextArea txt_area;
    // End of variables declaration//GEN-END:variables
}
