/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package charlesk.com.hospital_management_system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author charles
 */
public class Medicines extends javax.swing.JFrame {
    ResultSet rs;
    PreparedStatement pst;
    Connection con;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Medicines.class.getName());

    /**
     * Creates new form Medicines
     */
    public Medicines() {
        initComponents();
        setLocationRelativeTo(null);

        loadMedicines();
        showResultsInTheTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_last = new javax.swing.JButton();
        lbl_stock_quantity = new javax.swing.JLabel();
        txt_stock_quantity = new javax.swing.JTextField();
        txt_medicine_id = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();
        txt_unit_price = new javax.swing.JTextField();
        btn_previous = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicines_table = new javax.swing.JTable();
        btn_find = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        txt_form = new javax.swing.JTextField();
        lbl_form = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        lbl_unit_price = new javax.swing.JLabel();
        lbl_medicine_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_last.setText("LAST");
        btn_last.addActionListener(this::btn_lastActionPerformed);

        lbl_stock_quantity.setText("Stock Quantity");

        btn_next.setText("NEXT");
        btn_next.addActionListener(this::btn_nextActionPerformed);

        btn_previous.setText("PREVIOUS");
        btn_previous.addActionListener(this::btn_previousActionPerformed);

        medicines_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Medicine ID", "Medicine Name", "Form", "Unit Price", "Stock Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medicines_table);

        btn_find.setText("FIND");
        btn_find.addActionListener(this::btn_findActionPerformed);

        btn_save.setText("SAVE");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        txt_form.addActionListener(this::txt_formActionPerformed);

        lbl_form.setText("Form");

        lbl_name.setText("Medicine Name");

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        btn_back.setText("Back");
        btn_back.addActionListener(this::btn_backActionPerformed);

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(this::btn_exitActionPerformed);

        btn_first.setText("FIRST");
        btn_first.addActionListener(this::btn_firstActionPerformed);

        lbl_unit_price.setText("Unit Price");

        lbl_medicine_id.setText("Medicine ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_medicine_id, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_first)
                                .addGap(18, 18, 18)
                                .addComponent(btn_last)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_next)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_previous))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_clear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_exit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_find))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_unit_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lbl_stock_quantity))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_form, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(txt_unit_price, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(txt_medicine_id, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(txt_stock_quantity))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_back)
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_medicine_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_medicine_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_name)
                                .addGap(12, 12, 12)
                                .addComponent(lbl_form, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_unit_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_unit_price))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_stock_quantity)
                            .addComponent(txt_stock_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_save)
                            .addComponent(btn_clear)
                            .addComponent(btn_delete)
                            .addComponent(btn_exit)
                            .addComponent(btn_find))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_previous))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        try{
            if(rs != null && rs.last()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Results have not been loaded");
            else if(rs.next())
            displayCurrentRow();
            else{
                JOptionPane.showMessageDialog(this, "You are at the last row");
                rs.last();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Rocords are not loaded");

            else if(rs.previous()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "You are at the first record");
                rs.first();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_previousActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
    String medicine_id = txt_medicine_id.getText().trim();

    if(medicine_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the Medicine ID to search");
        txt_medicine_id.requestFocus();
        return;
    }

    String sql = "SELECT * FROM medicines WHERE medicine_id = ?";

    try(Connection findCon = DatabaseConnection.getConnection(); PreparedStatement findPst = findCon.prepareStatement(sql)){

        findPst.setString(1, medicine_id);

        try(ResultSet findRs = findPst.executeQuery()){

            if(findRs.next()){
                displayMedicine(findRs);
            }else{
                JOptionPane.showMessageDialog(this, "No medicine found with ID " + medicine_id);
            }
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error searching medicine: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
    String medicineName = txt_name.getText().trim();
    String form = txt_form.getText().trim();
    String unitPriceText = txt_unit_price.getText().trim();
    String stockText = txt_stock_quantity.getText().trim();

    if(medicineName.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the medicine name");
        txt_name.requestFocus();
        return;
    }else if(form.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the medicine form");
        txt_form.requestFocus();
        return;
    }else if(unitPriceText.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the unit price");
        txt_unit_price.requestFocus();
        return;
    }else if(stockText.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the stock quantity");
        txt_stock_quantity.requestFocus();
        return;
    }

    BigDecimal unitPrice;
    int stockQuantity;

    try{
        unitPrice = new BigDecimal(unitPriceText);

        if(unitPrice.compareTo(BigDecimal.ZERO) <= 0){
            JOptionPane.showMessageDialog(this, "Unit price must be greater than zero");
            txt_unit_price.requestFocus();
            return;
        }

    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Please enter a valid unit price");
        txt_unit_price.requestFocus();
        return;
    }

    try{
        stockQuantity = Integer.parseInt(stockText);

        if(stockQuantity < 0){
            JOptionPane.showMessageDialog(this, "Stock quantity cannot be negative");
            txt_stock_quantity.requestFocus();
            return;
        }

    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Please enter a valid stock quantity");
        txt_stock_quantity.requestFocus();
        return;
    }

    String sql = "INSERT INTO medicines(medicine_name, form, unit_price, stock_quantity) VALUES (?, ?, ?, ?)";

    try(Connection saveCon = DatabaseConnection.getConnection(); PreparedStatement savePst = saveCon.prepareStatement(sql)){

        savePst.setString(1, medicineName);
        savePst.setString(2, form);
        savePst.setBigDecimal(3, unitPrice);
        savePst.setInt(4, stockQuantity);

        int rows = savePst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Medicine successfully saved");
            clear();
            loadMedicines();
            showResultsInTheTable();
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error while saving medicine: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_formActionPerformed

    }//GEN-LAST:event_txt_formActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        try {
            clear();
            txt_form.requestFocus();

        } catch(SQLException e) {
            JOptionPane.showMessageDialog(this,"Error while clearing the interface" );
        }
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    String medicine_id = txt_medicine_id.getText().trim();

    if(medicine_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter or select a Medicine ID to delete");
        txt_medicine_id.requestFocus();
        return;
    }

    int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this medicine?", "Confirm deletion", JOptionPane.YES_NO_OPTION);

    if(choice != JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM medicines WHERE medicine_id = ?";

    try(Connection deleteCon = DatabaseConnection.getConnection(); PreparedStatement deletePst = deleteCon.prepareStatement(sql)){

        deletePst.setString(1, medicine_id);

        int rows = deletePst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Medicine deleted successfully");
            clear();
            loadMedicines();
            showResultsInTheTable();
        }else{
            JOptionPane.showMessageDialog(this, "No medicine with ID " + medicine_id + " exists in the database");
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Hospital_System().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        try{
            if(rs != null) rs.close();
            if(pst != null) pst.close();
            if(con != null) con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Problem while closing resources: " + e.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        try{
            if(rs != null && rs.first()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Medicines().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous;
    private javax.swing.JButton btn_save;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_form;
    private javax.swing.JLabel lbl_medicine_id;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_stock_quantity;
    private javax.swing.JLabel lbl_unit_price;
    private javax.swing.JTable medicines_table;
    private javax.swing.JTextField txt_form;
    private javax.swing.JTextField txt_medicine_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_stock_quantity;
    private javax.swing.JTextField txt_unit_price;
    // End of variables declaration//GEN-END:variables
public void displayMedicine(ResultSet data) throws SQLException{
    txt_medicine_id.setText(data.getString("medicine_id"));
    txt_name.setText(data.getString("medicine_name"));
    txt_form.setText(data.getString("form"));
    txt_unit_price.setText(data.getString("unit_price"));
    txt_stock_quantity.setText(data.getString("stock_quantity"));
}
public void clear() throws SQLException{
    txt_medicine_id.setText("");
    txt_name.setText("");
    txt_form.setText("");
    txt_unit_price.setText("");
    txt_stock_quantity.setText("");
    txt_name.requestFocus();
}
public void displayCurrentRow() throws SQLException{
    displayMedicine(rs);
}
public final void loadMedicines(){
    String sql = "SELECT * FROM medicines ORDER BY medicine_id";

    try{
        if(rs != null) rs.close();
        if(pst != null) pst.close();
        if(con != null) con.close();

        con = DatabaseConnection.getConnection();
        pst = con.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        rs = pst.executeQuery();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading medicines: " + e.getMessage());
    }
}
public final void showResultsInTheTable(){
    try{
        DefaultTableModel model = (DefaultTableModel) medicines_table.getModel();
        model.setRowCount(0);

        while(rs.next()){
            Object[] row = {
                rs.getString("medicine_id"),
                rs.getString("medicine_name"),
                rs.getString("form"),
                rs.getBigDecimal("unit_price"),
                rs.getInt("stock_quantity")
            };

            model.addRow(row);
        }

        rs.beforeFirst();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading medicines: " + e.getMessage());
    }
}
}
