/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package charlesk.com.hospital_management_system;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.io.IOException;
/**
 *
 * @author charles
 */
public class Nurses extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Nurses.class.getName());
    ResultSet rs;
    PreparedStatement pst;
    Connection con;
    String imagePath = null;
    

    /**
     * Creates new form Nurses
     */
    public Nurses() {
        initComponents();
        setLocationRelativeTo(null);
        
        combo_gender.setSelectedIndex(-1);
        combo_department.setSelectedIndex(-1);
        loadDepartments();
        
        loadNurses();
        showResultsInTheTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_last = new javax.swing.JButton();
        lbl_department_id = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        txt_nurse_id = new javax.swing.JTextField();
        combo_gender = new javax.swing.JComboBox<>();
        btn_next = new javax.swing.JButton();
        date_chooser = new com.toedter.calendar.JDateChooser();
        txt_phone = new javax.swing.JTextField();
        btn_previous = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nurses_table = new javax.swing.JTable();
        btn_find = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        txt_surname = new javax.swing.JTextField();
        lbl_surname = new javax.swing.JLabel();
        lbl_firstname = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        lbl_dob = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        lbl_nurse_id = new javax.swing.JLabel();
        txt_qualification = new javax.swing.JTextField();
        lbl_qualification = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_email1 = new javax.swing.JLabel();
        combo_department = new javax.swing.JComboBox<>();
        lbl_image = new javax.swing.JLabel();
        btn_choose_image = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_last.setText("LAST");
        btn_last.addActionListener(this::btn_lastActionPerformed);

        lbl_department_id.setText("Department_id");

        lbl_gender.setText("Gender");

        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        btn_next.setText("NEXT");
        btn_next.addActionListener(this::btn_nextActionPerformed);

        btn_previous.setText("PREVIOUS");
        btn_previous.addActionListener(this::btn_previousActionPerformed);

        nurses_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First name", "Last Name", "Gender", "Date of birth", "Phone", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(nurses_table);

        btn_find.setText("FIND");
        btn_find.addActionListener(this::btn_findActionPerformed);

        btn_save.setText("SAVE");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        txt_surname.addActionListener(this::txt_surnameActionPerformed);

        lbl_surname.setText("SurName");

        lbl_firstname.setText("First Name");

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        btn_back.setText("Back");
        btn_back.addActionListener(this::btn_backActionPerformed);

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(this::btn_exitActionPerformed);

        btn_first.setText("FIRST");
        btn_first.addActionListener(this::btn_firstActionPerformed);

        lbl_dob.setText("Date of birth");

        lbl_phone.setText("Phone");

        lbl_nurse_id.setText("Nurse Id");

        lbl_qualification.setText("Qualification");

        lbl_email1.setText("Email");

        lbl_image.setText("Image");

        btn_choose_image.setText("choose_image");
        btn_choose_image.addActionListener(this::btn_choose_imageActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_department_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_department, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(combo_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_nurse_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_firstname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(lbl_surname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nurse_id, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_back))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btn_choose_image)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57)
                                .addComponent(lbl_dob)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 17, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_first)
                        .addGap(18, 18, 18)
                        .addComponent(btn_last)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_next)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_previous))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_exit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_find)))
                .addGap(194, 194, 194))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_qualification, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_qualification, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_email1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_surname)
                                .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_firstname)
                                .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_dob))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_back)
                        .addGap(49, 49, 49)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nurse_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nurse_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_phone))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_department_id)
                            .addComponent(combo_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_gender)
                            .addComponent(combo_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_email1)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_qualification)
                            .addComponent(txt_qualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_choose_image)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear)
                    .addComponent(btn_delete)
                    .addComponent(btn_exit)
                    .addComponent(btn_find))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_previous))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        try{
            if(rs != null && rs.last()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Results have not been loaded");
            else if(rs.next())
            displayCurrentRow();
            else{
                JOptionPane.showMessageDialog(this, "You are at the last row");
                rs.last();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Rocords are not loaded");

            else if(rs.previous()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "You are at the first record");
                rs.first();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_previousActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed

    String nurse_id = txt_nurse_id.getText().trim();

    if(nurse_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the Nurse ID to search");
        txt_nurse_id.requestFocus();
        return;
    }

    String sql = "SELECT * FROM nurses WHERE nurse_id = ?";

    try(Connection searchCon = DatabaseConnection.getConnection(); PreparedStatement searchPst = searchCon.prepareStatement(sql)){

        searchPst.setString(1, nurse_id);

        try(ResultSet searchRs = searchPst.executeQuery()){

            if(searchRs.next()){
                txt_nurse_id.setText(searchRs.getString("nurse_id"));
                combo_department.setSelectedItem(searchRs.getString("department_id"));
                txt_firstname.setText(searchRs.getString("first_name"));
                txt_surname.setText(searchRs.getString("last_name"));
                txt_phone.setText(searchRs.getString("phone"));
                txt_email.setText(searchRs.getString("email"));
                txt_qualification.setText(searchRs.getString("qualification"));
                date_chooser.setDate(searchRs.getDate("date_of_birth"));
                combo_gender.setSelectedItem(searchRs.getString("gender"));
            }else{
                JOptionPane.showMessageDialog(this, "No nurse found with ID " + nurse_id);
            }
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error searching nurse: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

    String department_id = (String)combo_department.getSelectedItem();
    String firstname = txt_firstname.getText().trim();
    String surname = txt_surname.getText().trim();
    String phone = txt_phone.getText().trim();
    String email = txt_email.getText().trim();
    String qualification = txt_qualification.getText().trim();
    Object selectedGender = combo_gender.getSelectedItem();
    java.util.Date selectedDate = date_chooser.getDate();

    if(department_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please fill in the department ID");
        combo_department.requestFocus();
        return;
    }else if(firstname.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please fill in the firstname");
        txt_firstname.requestFocus();
        return;
    }else if(surname.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please fill in the surname");
        txt_surname.requestFocus();
        return;
    }else if(phone.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please fill in the phone");
        txt_phone.requestFocus();
        return;
    }else if(email.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please fill in the email");
        txt_email.requestFocus();
        return;
    }else if(qualification.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please fill in the qualification");
        txt_qualification.requestFocus();
        return;
    }else if(selectedDate == null){
        JOptionPane.showMessageDialog(this, "Please select date of birth");
        return;
    }else if(selectedGender == null){
        JOptionPane.showMessageDialog(this, "Please select gender");
        combo_gender.requestFocus();
        return;
    }

    String gender = selectedGender.toString();
    java.sql.Date dob = new java.sql.Date(selectedDate.getTime());
    String sql = "INSERT INTO nurses(department_id, first_name, last_name, phone, email, qualification, date_of_birth, gender) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

    try(Connection con = DatabaseConnection.getConnection(); PreparedStatement pst = con.prepareStatement(sql)){

        pst.setString(1, department_id);
        pst.setString(2, firstname);
        pst.setString(3, surname);
        pst.setString(4, phone);
        pst.setString(5, email);
        pst.setString(6, qualification);
        pst.setDate(7, dob);
        pst.setString(8, gender);

        int rows = pst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Nurse successfully saved");
            clear();
            loadNurses();
            showResultsInTheTable();
            txt_surname.requestFocus();
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error while saving nurse: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void txt_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_surnameActionPerformed

    }//GEN-LAST:event_txt_surnameActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
         try{
        clear();
        txt_surname.requestFocus();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error while clearing the interface");
    }
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    String nurse_id = txt_nurse_id.getText().trim();

    if(nurse_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter or select a Nurse ID to delete");
        txt_nurse_id.requestFocus();
        return;
    }

    int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this nurse?", "Confirm deletion", JOptionPane.YES_NO_OPTION);

    if(choice != JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM nurses WHERE nurse_id = ?";

    try(Connection con = DatabaseConnection.getConnection(); PreparedStatement pst = con.prepareStatement(sql)){

        pst.setString(1, nurse_id);
        int rows = pst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Nurse deleted successfully");
            clear();
            loadNurses();
            showResultsInTheTable();
            txt_surname.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this, "No nurse with ID " + nurse_id + " exists in the database");
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Hospital_System().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        try{
        if(rs != null) rs.close();
        if(pst != null) pst.close();
        if(con != null) con.close();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Problem while closing resources: " + e.getMessage());
    }
    System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        try{
        if(rs != null && rs.first()){
            displayCurrentRow();
        }else{
            JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
        }
    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error " + e.getMessage());
    }
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_choose_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choose_imageActionPerformed
        JFileChooser chooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png");

        chooser.setFileFilter(filter);

        int result = chooser.showOpenDialog(this);

        if(result == JFileChooser.APPROVE_OPTION){

            File selectedFile = chooser.getSelectedFile();

            try{
                Path nurseFolder = Paths.get("images", "nurses");

                Files.createDirectories(nurseFolder);

                String fileName = System.currentTimeMillis() + "_" + selectedFile.getName();

                Path destination = nurseFolder.resolve(fileName);

                Files.copy(
                    selectedFile.toPath(),
                    destination,
                    StandardCopyOption.REPLACE_EXISTING
                );

                imagePath = destination.toString();

                displayImage(imagePath);

            }catch(IOException e){
                JOptionPane.showMessageDialog(this, "Error copying image: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_choose_imageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Nurses().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_choose_image;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> combo_department;
    private javax.swing.JComboBox<String> combo_gender;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_department_id;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_email1;
    private javax.swing.JLabel lbl_firstname;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_nurse_id;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_qualification;
    private javax.swing.JLabel lbl_surname;
    private javax.swing.JTable nurses_table;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_nurse_id;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_qualification;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
public void clear() throws SQLException{
    txt_nurse_id.setText("");
    combo_department.setSelectedItem("");
    txt_firstname.setText("");
    txt_surname.setText("");
    txt_phone.setText("");
    txt_email.setText("");
    txt_qualification.setText("");
    date_chooser.setDate(null);
    combo_gender.setSelectedIndex(-1);
}
public void displayCurrentRow() throws SQLException{
    txt_nurse_id.setText(rs.getString("nurse_id"));
    combo_department.setSelectedItem(rs.getString("department_id"));
    txt_firstname.setText(rs.getString("first_name"));
    txt_surname.setText(rs.getString("last_name"));
    txt_phone.setText(rs.getString("phone"));
    txt_email.setText(rs.getString("email"));
    txt_qualification.setText(rs.getString("qualification"));
    date_chooser.setDate(rs.getDate("date_of_birth"));
    combo_gender.setSelectedItem(rs.getString("gender"));
}
public final void loadNurses(){
    String sql = "SELECT * FROM nurses ORDER BY nurse_id";

    try{
        con = DatabaseConnection.getConnection();
        pst = con.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        rs = pst.executeQuery();
    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading nurses information: " + e.getMessage());
    }
}
public final void showResultsInTheTable(){
    try{
        DefaultTableModel model = (DefaultTableModel) nurses_table.getModel();
        model.setRowCount(0);

        while(rs.next()){
            Object[] row = {
                rs.getString("nurse_id"),
                rs.getString("department_id"),
                rs.getString("first_name"),
                rs.getString("last_name"),
                rs.getString("phone"),
                rs.getString("email"),
                rs.getString("qualification"),
                rs.getDate("date_of_birth"),
                rs.getString("gender")
            };
            model.addRow(row);
        }

        rs.beforeFirst();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading nurses: " + e.getMessage());
    }
}
public void loadDepartments(){
    String sql = "SELECT department_id, department_name FROM departments ORDER BY department_id";

    try(Connection con = DatabaseConnection.getConnection(); 
            PreparedStatement pst = con.prepareStatement(sql); 
            ResultSet rs = pst.executeQuery())
    {
        combo_department.removeAllItems();

        while(rs.next()){
            combo_department.addItem(rs.getString("department_id") + " - " + rs.getString("department_name"));
        }

        combo_department.setSelectedIndex(-1);

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading departments: " + e.getMessage());
    }
}
public void displayImage(String path){

    if(path == null || path.trim().isEmpty()){
        lbl_image.setIcon(null);
        lbl_image.setText("No Image");
        return;
    }

    File imageFile = new File(path);

    if(!imageFile.exists()){
        lbl_image.setIcon(null);
        lbl_image.setText("Image Not Found");
        return;
    }

    ImageIcon icon = new ImageIcon(path);

    Image image = icon.getImage().getScaledInstance(
        lbl_image.getWidth(),
        lbl_image.getHeight(),
        Image.SCALE_SMOOTH
    );

    lbl_image.setText("");
    lbl_image.setIcon(new ImageIcon(image));
}

}
