/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package charlesk.com.hospital_management_system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author charles
 */
public class Prescriptions extends javax.swing.JFrame {
    ResultSet rs;
    PreparedStatement pst;
    Connection con;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Prescriptions.class.getName());

    /**
     * Creates new form Prescriptions
     */
    public Prescriptions() {
        initComponents();
        setLocationRelativeTo(null);

        loadAppointments();
        combo_appointment.setSelectedIndex(-1);

        loadPrescriptions();
        showResultsInTheTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_delete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        prescribed_date = new com.toedter.calendar.JDateChooser();
        btn_last = new javax.swing.JButton();
        lbl_prescription_date = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        lbl_prescription_id = new javax.swing.JLabel();
        lbl_appointment_id = new javax.swing.JLabel();
        txt_prescription_id = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();
        btn_find = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        combo_appointment = new javax.swing.JComboBox<>();
        btn_previous = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptions_table = new javax.swing.JTable();
        lbl_notes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_notes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        btn_back.setText("Back");
        btn_back.addActionListener(this::btn_backActionPerformed);

        btn_last.setText("LAST");
        btn_last.addActionListener(this::btn_lastActionPerformed);

        lbl_prescription_date.setText("Prescribed Date");

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(this::btn_exitActionPerformed);

        btn_first.setText("FIRST");
        btn_first.addActionListener(this::btn_firstActionPerformed);

        lbl_prescription_id.setText("Prescription ID");

        lbl_appointment_id.setText("Appointment ID");

        btn_next.setText("NEXT");
        btn_next.addActionListener(this::btn_nextActionPerformed);

        btn_find.setText("FIND");
        btn_find.addActionListener(this::btn_findActionPerformed);

        btn_save.setText("SAVE");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        btn_previous.setText("PREVIOUS");
        btn_previous.addActionListener(this::btn_previousActionPerformed);

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        prescriptions_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Prescription ID", "Appointment ID", "Prescribed Date", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(prescriptions_table);

        lbl_notes.setText("Notes");

        txt_notes.setColumns(20);
        txt_notes.setRows(5);
        jScrollPane2.setViewportView(txt_notes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_prescription_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_prescription_id, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_first)
                                .addGap(18, 18, 18)
                                .addComponent(btn_last)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_next)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_previous))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_prescription_date)
                                        .addGap(13, 13, 13)
                                        .addComponent(prescribed_date, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_save)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_clear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_delete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_exit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_find))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_appointment_id)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(combo_appointment, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btn_back))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_prescription_id)
                            .addComponent(txt_prescription_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_appointment_id)
                    .addComponent(combo_appointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prescribed_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_prescription_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_notes)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear)
                    .addComponent(btn_delete)
                    .addComponent(btn_exit)
                    .addComponent(btn_find))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_first)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_previous))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    String prescription_id = txt_prescription_id.getText().trim();

    if(prescription_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter or select a Prescription ID to delete");
        txt_prescription_id.requestFocus();
        return;
    }

    int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this prescription?", "Confirm deletion", JOptionPane.YES_NO_OPTION);

    if(choice != JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM prescriptions WHERE prescription_id = ?";

    try(Connection deleteCon = DatabaseConnection.getConnection(); PreparedStatement deletePst = deleteCon.prepareStatement(sql)){

        deletePst.setString(1, prescription_id);
        int rows = deletePst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Prescription deleted successfully");
            clear();
            loadPrescriptions();
            showResultsInTheTable();
        }else{
            JOptionPane.showMessageDialog(this, "No prescription with ID " + prescription_id + " exists in the database");
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Hospital_System().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        try{
            if(rs != null && rs.last()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        try{
            if(rs != null) rs.close();
            if(pst != null) pst.close();
            if(con != null) con.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Problem while closing resources: " + e.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        try{
            if(rs != null && rs.first()){
                displayCurrentRow();
            }else{
                JOptionPane.showMessageDialog(this, "Empty database, nothing to retrieve");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Results have not been loaded");
            else if(rs.next())
            displayCurrentRow();
            else{
                JOptionPane.showMessageDialog(this, "You are at the last row");
                rs.last();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
    String prescription_id = txt_prescription_id.getText().trim();

    if(prescription_id.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please enter the Prescription ID to search");
        txt_prescription_id.requestFocus();
        return;
    }

    String sql = "SELECT * FROM prescriptions WHERE prescription_id = ?";

    try(Connection findCon = DatabaseConnection.getConnection(); PreparedStatement findPst = findCon.prepareStatement(sql)){

        findPst.setString(1, prescription_id);

        try(ResultSet findRs = findPst.executeQuery()){

            if(findRs.next()){
                displayPrescription(findRs);
            }else{
                JOptionPane.showMessageDialog(this, "No prescription found with ID " + prescription_id);
            }
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error searching prescription: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
    Object appointment = combo_appointment.getSelectedItem();
    java.util.Date selectedDate = prescribed_date.getDate();
    String notes = txt_notes.getText().trim();

    if(appointment == null){
        JOptionPane.showMessageDialog(this, "Please select an appointment");
        combo_appointment.requestFocus();
        return;
    }else if(selectedDate == null){
        JOptionPane.showMessageDialog(this, "Please select the prescribed date");
        return;
    }

    String appointment_id = appointment.toString().split(" - ")[0];
    java.sql.Date prescribedDate = new java.sql.Date(selectedDate.getTime());

    String sql = "INSERT INTO prescriptions(appointment_id, prescribed_date, notes) VALUES (?, ?, ?)";

    try(Connection saveCon = DatabaseConnection.getConnection(); PreparedStatement savePst = saveCon.prepareStatement(sql)){

        savePst.setString(1, appointment_id);
        savePst.setDate(2, prescribedDate);

        if(notes.isEmpty()) savePst.setNull(3, java.sql.Types.VARCHAR);
        else savePst.setString(3, notes);

        int rows = savePst.executeUpdate();

        if(rows > 0){
            JOptionPane.showMessageDialog(this, "Prescription successfully saved");
            clear();
            loadPrescriptions();
            showResultsInTheTable();
        }

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error while saving prescription: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        try{
            if(rs == null)
            JOptionPane.showMessageDialog(this, "Rocords are not loaded");

            else if(rs.previous()){
                displayCurrentRow();
            }
            else{
                JOptionPane.showMessageDialog(this, "You are at the first record");
                rs.first();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this , "Error " + e.getMessage());
        }
    }//GEN-LAST:event_btn_previousActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        try{
            clear();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error while clearing the interface");
        }
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Prescriptions().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_previous;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> combo_appointment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_appointment_id;
    private javax.swing.JLabel lbl_notes;
    private javax.swing.JLabel lbl_prescription_date;
    private javax.swing.JLabel lbl_prescription_id;
    private com.toedter.calendar.JDateChooser prescribed_date;
    private javax.swing.JTable prescriptions_table;
    private javax.swing.JTextArea txt_notes;
    private javax.swing.JTextField txt_prescription_id;
    // End of variables declaration//GEN-END:variables
public void loadAppointments(){
    String sql = """
                 SELECT a.appointment_id, 
                 CONCAT(p.first_name, ' ', p.last_name) AS full_name
                 FROM appointments a 
                 INNER JOIN patients p ON a.patient_id = p.patient_id 
                 ORDER BY a.appointment_id                                                                                                                                                    
                """;

    try(Connection appointmentCon = DatabaseConnection.getConnection(); 
            PreparedStatement appointmentPst = appointmentCon.prepareStatement(sql); 
            ResultSet appointmentRs = appointmentPst.executeQuery())
    {

        combo_appointment.removeAllItems();

        while(appointmentRs.next()){
            combo_appointment.addItem(appointmentRs.getString("appointment_id") + " - " + appointmentRs.getString("full_name"));
        }

        combo_appointment.setSelectedIndex(-1);

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading appointments: " + e.getMessage());
    }
}
public void displayPrescription(ResultSet data) throws SQLException{
    txt_prescription_id.setText(data.getString("prescription_id"));
    selectAppointment(data.getString("appointment_id"));
    prescribed_date.setDate(data.getDate("prescribed_date"));
    txt_notes.setText(data.getString("notes") == null ? "" : data.getString("notes"));
}
public void selectAppointment(String appointment_id){
    for(int i = 0; i < combo_appointment.getItemCount(); i++){
        if(combo_appointment.getItemAt(i).startsWith(appointment_id + " - ")){
            combo_appointment.setSelectedIndex(i);
            break;
        }
    }
}
public void clear() throws SQLException{
    txt_prescription_id.setText("");
    combo_appointment.setSelectedIndex(-1);
    prescribed_date.setDate(null);
    txt_notes.setText("");
}
public void displayCurrentRow() throws SQLException{
    displayPrescription(rs);
}
public final void loadPrescriptions(){
    String sql = "SELECT * FROM prescriptions ORDER BY prescription_id";

    try{
        if(rs != null) rs.close();
        if(pst != null) pst.close();
        if(con != null) con.close();

        con = DatabaseConnection.getConnection();
        pst = con.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        rs = pst.executeQuery();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading prescriptions: " + e.getMessage());
    }
}
public final void showResultsInTheTable(){
    try{
        DefaultTableModel model = (DefaultTableModel) prescriptions_table.getModel();
        model.setRowCount(0);

        while(rs.next()){
            Object[] row = {
                rs.getString("prescription_id"),
                rs.getString("appointment_id"),
                rs.getDate("prescribed_date"),
                rs.getString("notes")
            };

            model.addRow(row);
        }

        rs.beforeFirst();

    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Error loading prescriptions: " + e.getMessage());
    }
}
}
